# Generated by Django 5.1.15 on 2026-09-18 00:00
#
# NOTE the field is nullable with no default, and that is the whole point of
# it. Null means "sell cabins per head" — the behaviour every ship has today.
# Giving it a value here would re-price every cabin the moment this migration
# ran, which is not a decision a deployment gets to make.

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0018_ship_default_adult_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='meal_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Leave blank to charge per person. Set it to sell whole cabins, returning this much for each empty adult berth — the food that guest would have eaten over the trip.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
