# Generated by Django 5.1.15 on 2026-08-28 06:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_foreigner_surcharge_global'),
        ('ships', '0016_fix_mv_crown_room_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Displayed star rating out of 5, e.g. 4.8. Leave blank to hide.', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
        # A pre-existing excl_ship_package_date_overlap constraint drift shows
        # up here too (Django's migration state doesn't match the DB) — left
        # out deliberately: the constraint already exists, and AddConstraint
        # would fail against it. Unrelated to this migration's actual change.
    ]
