# Generated by Django 5.1.15 on 2026-09-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_seed_default_cancellation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='gateway_checked_at',
            field=models.DateTimeField(blank=True, help_text='Last time the gateway was asked about this.', null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='gateway_payload',
            field=models.JSONField(blank=True, default=dict, help_text="The gateway's last answer, verbatim, for when a figure is disputed."),
        ),
        migrations.AddField(
            model_name='refund',
            name='gateway_refund_status',
            field=models.CharField(blank=True, choices=[('processing', 'In processing at the gateway'), ('refunded', 'Refunded — the customer has the money'), ('cancelled', 'Cancelled by the gateway — money NOT returned')], help_text='Blank until the gateway has been asked. Not the same as processing.', max_length=12),
        ),
        migrations.AddField(
            model_name='refund',
            name='gateway_refunded_at',
            field=models.DateTimeField(blank=True, help_text='When the gateway says the money actually reached the customer.', null=True),
        ),
    ]
