# Generated by Django 5.1.15 on 2026-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_risk_level',
            field=models.SmallIntegerField(blank=True, help_text='SSLCommerz risk_level: 0 = normal, 1 = risky (verify the customer before delivering the service). Blank if the gateway reported none.', null=True),
        ),
    ]
